name: Build Pull Request

on:
  pull_request:
    branches: [main]
  push:
  workflow_dispatch:

jobs:
  build:
    name: build (x86_64)
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          brew install cmake ninja openssl zlib

      - name: Configure
        run: |
          cmake -B build -G Ninja \
            -DOPENSSL_ROOT_DIR="$(brew --prefix openssl)" \
            -DZLIB_ROOT="$(brew --prefix zlib)"

      - name: Build
        run: cmake --build build
